# Generated by Django 4.1.4 on 2022-12-25 01:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championnat',
            fields=[
                ('id_champ', models.AutoField(auto_created=True, db_column='ID_CHAMP', primary_key=True, serialize=False)),
                ('nomchamp', models.TextField(db_column='NOMCHAMP')),
                ('season', models.TextField(db_column='SEASON')),
                ('TypeChamp', models.TextField(db_column='TYPECHAMP')),
            ],
            options={
                'db_table': 'championnat',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(auto_created=True, db_column='ID_CLUB', primary_key=True, serialize=False)),
                ('nomclub', models.TextField(db_column='NOMCLUB')),
                ('image', models.TextField(blank=True, db_column='IMAGE', null=True)),
                ('paysclub', models.TextField(blank=True, db_column='PAYSCLUB', null=True)),
                ('villeclub', models.TextField(blank=True, db_column='VILLECLUB', null=True)),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Equipenational',
            fields=[
                ('id_equipe', models.AutoField(auto_created=True, db_column='ID_EQUIPE', primary_key=True, serialize=False)),
                ('nomequipe', models.TextField(blank=True, db_column='NOMEQUIPE', null=True)),
                ('pays', models.TextField(db_column='PAYS')),
                ('image', models.TextField(blank=True, db_column='IMAGE', null=True)),
            ],
            options={
                'db_table': 'equipenational',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id_game', models.AutoField(auto_created=True, db_column='ID_GAME', primary_key=True, serialize=False)),
                ('phase', models.TextField(blank=True, db_column='PHASE', null=True)),
                ('datematch', models.DateField(blank=True, db_column='DATEMATCH', null=True)),
                ('id_champ', models.ForeignKey(db_column='ID_CHAMP', on_delete=django.db.models.deletion.DO_NOTHING, to='base.championnat')),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id_sponsor', models.AutoField(auto_created=True, db_column='ID_SPONSOR', primary_key=True, serialize=False)),
                ('nomsponsor', models.TextField(blank=True, db_column='NOMSPONSOR', null=True)),
                ('ville', models.TextField(blank=True, db_column='VILLE', null=True)),
                ('image', models.TextField(blank=True, db_column='IMAGE', null=True)),
            ],
            options={
                'db_table': 'sponsor',
            },
        ),
        migrations.CreateModel(
            name='SponsorEquipe',
            fields=[
                ('id_sponsor_equipe', models.AutoField(auto_created=True, db_column='ID_SPONSOR_EQUIPE', primary_key=True, serialize=False)),
                ('montant', models.FloatField(blank=True, db_column='MONTANT', null=True)),
                ('date_debut', models.DateField(blank=True, db_column='DATE_DEBUT', null=True)),
                ('date_fin', models.DateField(blank=True, db_column='DATE_FIN', null=True)),
                ('id_equipe', models.ForeignKey(db_column='ID_EQUIPE', on_delete=django.db.models.deletion.DO_NOTHING, to='base.equipenational')),
                ('id_sponsor', models.ForeignKey(db_column='ID_SPONSOR', on_delete=django.db.models.deletion.DO_NOTHING, to='base.sponsor')),
            ],
            options={
                'db_table': 'sponsor_equipe',
            },
        ),
        migrations.CreateModel(
            name='SponsorClub',
            fields=[
                ('id_sponsor_club', models.AutoField(auto_created=True, db_column='ID_SPONSOR_CLUB', primary_key=True, serialize=False)),
                ('montant', models.FloatField(blank=True, db_column='MONTANT', null=True)),
                ('date_debut', models.DateField(blank=True, db_column='DATE_DEBUT', null=True)),
                ('date_fin', models.DateField(blank=True, db_column='DATE_FIN', null=True)),
                ('id_club', models.ForeignKey(db_column='ID_CLUB', on_delete=django.db.models.deletion.DO_NOTHING, to='base.club')),
                ('id_sponsor', models.ForeignKey(db_column='ID_SPONSOR', on_delete=django.db.models.deletion.DO_NOTHING, to='base.sponsor')),
            ],
            options={
                'db_table': 'sponsor_club',
            },
        ),
        migrations.CreateModel(
            name='ParticipeLeague',
            fields=[
                ('id_equipe_club', models.AutoField(auto_created=True, db_column='ID_EQUIPE_CLUB', primary_key=True, serialize=False)),
                ('id_champ', models.ForeignKey(db_column='ID_CHAMP', on_delete=django.db.models.deletion.DO_NOTHING, to='base.championnat')),
                ('id_club', models.ForeignKey(db_column='ID_CLUB', on_delete=django.db.models.deletion.DO_NOTHING, to='base.club')),
            ],
            options={
                'db_table': 'participe_league',
            },
        ),
        migrations.CreateModel(
            name='ParticipeChamp',
            fields=[
                ('id_equipe_champ', models.AutoField(auto_created=True, db_column='ID_EQUIPE_CHAMP', primary_key=True, serialize=False)),
                ('id_champ', models.ForeignKey(db_column='ID_CHAMP', on_delete=django.db.models.deletion.DO_NOTHING, to='base.championnat')),
                ('id_equipe', models.ForeignKey(db_column='ID_EQUIPE', on_delete=django.db.models.deletion.DO_NOTHING, to='base.equipenational')),
            ],
            options={
                'db_table': 'participe_champ',
            },
        ),
        migrations.CreateModel(
            name='Matchequipe',
            fields=[
                ('id_equipe_game', models.AutoField(auto_created=True, db_column='ID_EQUIPE_GAME', primary_key=True, serialize=False)),
                ('type', models.TextField(db_column='Type')),
                ('score', models.IntegerField(blank=True, db_column='SCORE', null=True)),
                ('id_equipe', models.ForeignKey(db_column='ID_EQUIPE', on_delete=django.db.models.deletion.DO_NOTHING, to='base.equipenational')),
                ('id_game', models.ForeignKey(db_column='ID_GAME', on_delete=django.db.models.deletion.DO_NOTHING, to='base.game')),
            ],
            options={
                'db_table': 'matchequipe',
            },
        ),
        migrations.CreateModel(
            name='Matchclub',
            fields=[
                ('id_club_game', models.AutoField(auto_created=True, db_column='ID_CLUB_GAME', primary_key=True, serialize=False)),
                ('type', models.TextField(db_column='Type')),
                ('score', models.IntegerField(blank=True, db_column='SCORE', null=True)),
                ('id_club', models.ForeignKey(db_column='ID_CLUB', on_delete=django.db.models.deletion.DO_NOTHING, to='base.club')),
                ('id_game', models.ForeignKey(db_column='ID_GAME', on_delete=django.db.models.deletion.DO_NOTHING, to='base.game')),
            ],
            options={
                'db_table': 'matchclub',
            },
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id_joueur', models.AutoField(auto_created=True, db_column='ID_JOUEUR', primary_key=True, serialize=False)),
                ('nomjoueur', models.TextField(db_column='NOMJOUEUR')),
                ('image', models.TextField(blank=True, db_column='IMAGE', null=True)),
                ('prenomjoueur', models.TextField(db_column='PRENOMJOUEUR')),
                ('datenaiss', models.DateField(db_column='DATENAISS')),
                ('nationalite', models.TextField(db_column='NATIONALITE')),
                ('taillejoueur', models.FloatField(blank=True, db_column='TAILLEJOUEUR', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.2)])),
                ('date_debut_eq', models.DateField(blank=True, db_column='DATE_DEBUT_Eq', null=True)),
                ('date_fin_eq', models.DateField(blank=True, db_column='DATE_FIN_Eq', null=True)),
                ('date_debut_cl', models.DateField(blank=True, db_column='DATE_DEBUT_Cl', null=True)),
                ('date_fin_cl', models.DateField(blank=True, db_column='DATE_FIN_Cl', null=True)),
                ('id_club', models.ForeignKey(db_column='ID_CLUB', on_delete=django.db.models.deletion.DO_NOTHING, to='base.club')),
                ('id_equipe', models.ForeignKey(blank=True, db_column='ID_EQUIPE', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.equipenational')),
            ],
            options={
                'db_table': 'joueur',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.AutoField(auto_created=True, db_column='ID_EVALUATION', primary_key=True, serialize=False)),
                ('nombpt1', models.IntegerField(db_column='NOMBPT1')),
                ('nombpt2', models.IntegerField(db_column='NOMBPT2')),
                ('nombpt3', models.IntegerField(db_column='NOMBPT3')),
                ('nombptr1', models.IntegerField(db_column='NOMBPTR1')),
                ('nombptr2', models.IntegerField(blank=True, db_column='NOMBPTR2', null=True)),
                ('nombptr3', models.IntegerField(blank=True, db_column='NOMBPTR3', null=True)),
                ('nombreb', models.IntegerField(blank=True, db_column='NOMBREB', null=True)),
                ('nombpassd', models.IntegerField(db_column='NOMBPASSD')),
                ('nombctre', models.IntegerField(blank=True, db_column='NOMBCTRE', null=True)),
                ('nombfaute', models.IntegerField(blank=True, db_column='NOMBFAUTE', null=True)),
                ('id_game', models.ForeignKey(db_column='ID_GAME', on_delete=django.db.models.deletion.DO_NOTHING, to='base.game')),
                ('id_joueur', models.ForeignKey(blank=True, db_column='ID_JOUEUR', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.joueur')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Contribue',
            fields=[
                ('id_joueur_game', models.AutoField(auto_created=True, db_column='ID_CLUB_GAME', primary_key=True, serialize=False)),
                ('id_game', models.ForeignKey(db_column='ID_GAME', on_delete=django.db.models.deletion.DO_NOTHING, to='base.game')),
                ('id_joueur', models.ForeignKey(db_column='ID_JOUEUR', on_delete=django.db.models.deletion.DO_NOTHING, to='base.joueur')),
            ],
            options={
                'db_table': 'contribue',
            },
        ),
    ]
